laguage: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - "pip install behave --user"
  - "pip install --user -r requirements.txt"
script:
  - "python app.py &"
  - "python -m behave tests/acceptance"
