laguage: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - "pip install pytest --user"
  - "pip install --user -r requirements.txt"
script:
  - "python app.py &"
  - "python3.7.1 -m pytest tests/acceptance/"
