laguage: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - "pip install behave --user"
  - "pip install --user -r requirements.txt"
before_script:
  - "wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_win32.zip"
  - "unzip chromedriver_win32.zip -d /home/travis/virtualenv/python3.7/Scripts/"
  - "setx path '%path%;/home/travis/virtualenv/python3.7/Scripts/chromedriver.exe'"
script:
  - "python app.py &"
  - "python -m behave tests/acceptance"
